# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kHLxPLzX5jpm0g0bM57DXpg8PzegdirY
"""

"""
Script corrigido para o CSV do IBAMA mostrado pelo usuário.
Objetivo:
- Ler apenas o relatorio.csv do IBAMA
- Usar o layout real do arquivo para não perder UNIDADE e MODAL
- Filtrar anos 2023, 2024 e 2025
- Filtrar registros ligados a SP
- Gerar um CSV de saída com os campos certos

Saída:
saida_ibama_corrigido/base_filtrada_ibama_2023_2025_sp.csv
"""

from __future__ import annotations

import csv
import re
import sys
import unicodedata
from pathlib import Path
from typing import Optional

import pandas as pd


IBAMA_CSV_PATH: Optional[str] = None
AUTO_SEARCH = True

ANOS_DESEJADOS = {2023, 2024, 2025}
UF_FOCO = "SP"

OUTPUT_DIR_NAME = "saida_ibama_corrigido"
OUTPUT_CSV_NAME = "base_filtrada_ibama_2023_2025_sp.csv"

CHUNK_SIZE = 200_000


def log(msg: str) -> None:
    print(msg, flush=True)


def normalize_text(value: object) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    text = str(value).strip()
    if not text:
        return ""
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.replace("\n", " ").replace("\r", " ").replace("\t", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def normalize_col(col: object) -> str:
    text = normalize_text(col).lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    text = re.sub(r"_+", "_", text).strip("_")
    return text


def detect_encoding(file_path: Path) -> str:
    raw = file_path.read_bytes()[:100_000]
    for enc in ["utf-8-sig", "utf-8", "cp1252", "latin1"]:
        try:
            raw.decode(enc)
            return enc
        except UnicodeDecodeError:
            continue
    return "latin1"


def detect_separator(file_path: Path, encoding: str) -> str:
    sample = file_path.read_text(encoding=encoding, errors="ignore")[:20000]
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=";,|\t")
        return dialect.delimiter
    except Exception:
        counts = {sep: sample.count(sep) for sep in [";", ",", "|", "\t"]}
        best = max(counts, key=counts.get)
        return best if counts[best] > 0 else ";"


def clean_series(series: pd.Series) -> pd.Series:
    return series.astype("string").fillna("").map(normalize_text)


def to_year_series(series: pd.Series) -> pd.Series:
    extracted = (
        series.astype("string")
        .fillna("")
        .str.extract(r"(\d{4})", expand=False)
    )
    return pd.to_numeric(extracted, errors="coerce").astype("Int64")


def combine_uf_municipio(uf: pd.Series, municipio: pd.Series) -> pd.Series:
    uf_clean = clean_series(uf).str.upper()
    mun_clean = clean_series(municipio)
    return mun_clean.where(mun_clean.ne(""), uf_clean).where(
        mun_clean.eq(""), mun_clean + " - " + uf_clean
    )


def classify_product(text_series: pd.Series) -> pd.Series:
    s = clean_series(text_series).str.lower()
    combustivel = (
        s.str.contains("combust", na=False)
        | s.str.contains("gasolina", na=False)
        | s.str.contains("etanol", na=False)
        | s.str.contains("alcool", na=False)
        | s.str.contains("diesel", na=False)
        | s.str.contains("oleo diesel", na=False)
        | s.str.contains("querosene", na=False)
        | s.str.contains("glp", na=False)
        | s.str.contains("gpl", na=False)
    )
    return pd.Series(
        ["Combustível" if x else "Carga perigosa" for x in combustivel],
        index=text_series.index,
        dtype="string",
    )


def classify_action_plan(plan_series: pd.Series) -> pd.Series:
    s = clean_series(plan_series).str.lower()
    has_plan = (
        s.str.contains("sim", na=False)
        | s.str.contains("possui", na=False)
        | s.str.contains("plano", na=False)
        | s.str.contains("emerg", na=False)
    )
    return pd.Series(
        ["Plano informado" if x else "Sem informação clara" for x in has_plan],
        index=plan_series.index,
        dtype="string",
    )


def find_ibama_csv(base_dir: Path) -> Optional[Path]:
    candidates = []
    for path in base_dir.rglob("*.csv"):
        if OUTPUT_DIR_NAME.lower() in {p.lower() for p in path.parts}:
            continue
        name = path.name.lower()
        if name == "relatorio.csv":
            return path
        if "ibama" in name or "rapp" in name or "relatorio" in name:
            candidates.append(path)
    return candidates[0] if candidates else None


def rename_by_real_layout(df: pd.DataFrame) -> pd.DataFrame:
    """
    Usa o layout real mostrado pelo usuário.
    Mesmo que os nomes venham com acento quebrado no Excel,
    a ordem do arquivo do IBAMA costuma ser esta:

    0  CNPJ
    1  Razão Social
    2  Estado
    3  Município
    4  Ano
    5  Produto
    6  Quantidade
    7  Unidade ...
    8  Tipo de Tr...
    9  Tipo de Ar...
    10 Plano de E...
    11 UF - origem
    12 Município - origem
    13 UF - destino
    14 Município - destino
    15 Situação Cadastral
    """
    df = df.copy()
    original_cols = list(df.columns)
    norm_cols = [normalize_col(c) for c in original_cols]

    # tentativa 1: mapear por nomes/fragmentos
    target_map = {}

    for orig, norm in zip(original_cols, norm_cols):
        if norm == "cnpj":
            target_map[orig] = "cnpj"
        elif "razao" in norm or "social" in norm:
            target_map[orig] = "empresa"
        elif norm == "estado":
            target_map[orig] = "uf_estabelecimento"
        elif ("municip" in norm or "munic" in norm) and "orig" not in norm and "dest" not in norm:
            target_map[orig] = "municipio_estabelecimento"
        elif norm == "ano":
            target_map[orig] = "ano_ref"
        elif norm == "produto":
            target_map[orig] = "produto"
        elif "quantidad" in norm:
            target_map[orig] = "quantidade"
        elif "unidad" in norm:
            target_map[orig] = "unidade_medida"
        elif "tipo_de_tr" in norm or "tipo_tr" in norm or "tipo_de_trans" in norm or "tipo_trans" in norm:
            target_map[orig] = "modal"
        elif "tipo_de_ar" in norm or "tipo_ar" in norm or "armazen" in norm:
            target_map[orig] = "armazenamento"
        elif "plano" in norm:
            target_map[orig] = "plano_acao"
        elif "uf_orige" in norm or ("uf" in norm and "orig" in norm):
            target_map[orig] = "uf_origem"
        elif ("municip" in norm or "munic" in norm) and "orig" in norm:
            target_map[orig] = "municipio_origem"
        elif "uf_desti" in norm or ("uf" in norm and "dest" in norm):
            target_map[orig] = "uf_destino"
        elif ("municip" in norm or "munic" in norm) and "dest" in norm:
            target_map[orig] = "municipio_destino"
        elif "situacao" in norm or "cadastral" in norm:
            target_map[orig] = "situacao_cadastral"

    df = df.rename(columns=target_map)

    # tentativa 2: se ainda faltou algo importante, usar posição
    cols = list(df.columns)
    position_targets = {
        0: "cnpj",
        1: "empresa",
        2: "uf_estabelecimento",
        3: "municipio_estabelecimento",
        4: "ano_ref",
        5: "produto",
        6: "quantidade",
        7: "unidade_medida",
        8: "modal",
        9: "armazenamento",
        10: "plano_acao",
        11: "uf_origem",
        12: "municipio_origem",
        13: "uf_destino",
        14: "municipio_destino",
        15: "situacao_cadastral",
    }

    for idx, target in position_targets.items():
        if target not in df.columns and idx < len(cols):
            current_col = cols[idx]
            if current_col not in position_targets.values():
                df = df.rename(columns={current_col: target})

    # remove duplicadas
    if df.columns.duplicated().any():
        df = df.loc[:, ~df.columns.duplicated()].copy()

    # garante colunas finais
    needed = [
        "cnpj",
        "empresa",
        "uf_estabelecimento",
        "municipio_estabelecimento",
        "ano_ref",
        "produto",
        "quantidade",
        "unidade_medida",
        "modal",
        "armazenamento",
        "plano_acao",
        "uf_origem",
        "municipio_origem",
        "uf_destino",
        "municipio_destino",
        "situacao_cadastral",
    ]
    for col in needed:
        if col not in df.columns:
            df[col] = pd.NA

    return df


FINAL_COLUMNS = [
    "fonte",
    "tipo_registro",
    "ano_ref",
    "uf",
    "municipio",
    "empresa",
    "cnpj",
    "produto",
    "categoria",
    "quantidade",
    "unidade_medida",
    "modal",
    "origem",
    "destino",
    "armazenamento",
    "plano_acao",
    "situacao_cadastral",
]


def process_chunk(df: pd.DataFrame) -> pd.DataFrame:
    df = rename_by_real_layout(df)

    ano = to_year_series(df["ano_ref"])
    empresa = clean_series(df["empresa"])
    cnpj = clean_series(df["cnpj"])
    uf_estab = clean_series(df["uf_estabelecimento"]).str.upper()
    mun_estab = clean_series(df["municipio_estabelecimento"])
    produto = clean_series(df["produto"])
    quantidade = pd.to_numeric(df["quantidade"], errors="coerce")
    unidade = clean_series(df["unidade_medida"])
    modal = clean_series(df["modal"])
    armazenamento = clean_series(df["armazenamento"])
    plano = clean_series(df["plano_acao"])
    uf_origem = clean_series(df["uf_origem"]).str.upper()
    mun_origem = clean_series(df["municipio_origem"])
    uf_destino = clean_series(df["uf_destino"]).str.upper()
    mun_destino = clean_series(df["municipio_destino"])
    situacao = clean_series(df["situacao_cadastral"])

    mask_year = ano.isin(list(ANOS_DESEJADOS))
    mask_sp = (
        uf_estab.eq(UF_FOCO)
        | uf_origem.eq(UF_FOCO)
        | uf_destino.eq(UF_FOCO)
        | mun_estab.str.lower().eq("sao paulo")
        | mun_origem.str.lower().eq("sao paulo")
        | mun_destino.str.lower().eq("sao paulo")
    )
    mask = mask_year & mask_sp

    if not mask.any():
        return pd.DataFrame(columns=FINAL_COLUMNS)

    uf_main = uf_estab.mask(uf_estab.eq(""), uf_origem).mask(
        uf_estab.eq("") & uf_origem.eq(""), uf_destino
    )
    mun_main = mun_estab.mask(mun_estab.eq(""), mun_origem).mask(
        mun_estab.eq("") & mun_origem.eq(""), mun_destino
    )

    out = pd.DataFrame({
        "fonte": "IBAMA",
        "tipo_registro": "transporte_armazenamento",
        "ano_ref": ano,
        "uf": uf_main,
        "municipio": mun_main,
        "empresa": empresa,
        "cnpj": cnpj,
        "produto": produto,
        "categoria": classify_product(produto),
        "quantidade": quantidade,
        "unidade_medida": unidade,
        "modal": modal,
        "origem": combine_uf_municipio(uf_origem, mun_origem),
        "destino": combine_uf_municipio(uf_destino, mun_destino),
        "armazenamento": armazenamento,
        "plano_acao": classify_action_plan(plano),
        "situacao_cadastral": situacao,
    })

    out = out[mask].copy().drop_duplicates()
    return out


def main() -> None:
    base_dir = Path(__file__).resolve().parent
    output_dir = base_dir / OUTPUT_DIR_NAME
    output_dir.mkdir(parents=True, exist_ok=True)

    if IBAMA_CSV_PATH:
        csv_path = Path(IBAMA_CSV_PATH)
    elif AUTO_SEARCH:
        csv_path = find_ibama_csv(base_dir)
    else:
        csv_path = None

    if csv_path is None or not csv_path.exists():
        raise FileNotFoundError(
            "Não encontrei o CSV do IBAMA. Coloque o relatorio.csv na mesma pasta do .py "
            "ou preencha IBAMA_CSV_PATH."
        )

    encoding = detect_encoding(csv_path)
    sep = detect_separator(csv_path, encoding)

    log(f"[IBAMA] Arquivo: {csv_path}")
    log(f"[IBAMA] Encoding detectado: {encoding}")
    log(f"[IBAMA] Separador detectado: {repr(sep)}")

    total_lido = 0
    total_mantido = 0
    parts = []

    reader = pd.read_csv(
        csv_path,
        sep=sep,
        encoding=encoding,
        dtype="string",
        chunksize=CHUNK_SIZE,
        engine="python",
    )

    for i, chunk in enumerate(reader, start=1):
        total_lido += len(chunk)
        out = process_chunk(chunk)
        total_mantido += len(out)
        if not out.empty:
            parts.append(out)
        log(f"[IBAMA] Chunk {i}: lidas={len(chunk):,} | mantidas={len(out):,}")

    if parts:
        final = pd.concat(parts, ignore_index=True).drop_duplicates()
    else:
        final = pd.DataFrame(columns=FINAL_COLUMNS)

    final["ano_ref"] = pd.to_numeric(final["ano_ref"], errors="coerce").astype("Int64")
    final["quantidade"] = pd.to_numeric(final["quantidade"], errors="coerce")

    anos = sorted(final["ano_ref"].dropna().astype(int).unique().tolist()) if not final.empty else []
    log(f"[IBAMA] Total lido: {total_lido:,}")
    log(f"[IBAMA] Total mantido: {total_mantido:,}")
    log(f"[IBAMA] Anos encontrados após filtro: {anos}")

    output_path = output_dir / OUTPUT_CSV_NAME
    final.to_csv(output_path, index=False, sep=";", encoding="utf-8-sig")
    log(f"[OK] Arquivo final gerado: {output_path}")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        log("\n[INTERROMPIDO] Execução cancelada pelo usuário.")
        sys.exit(1)
    except Exception as exc:
        log(f"\n[ERRO] {exc}")
        sys.exit(1)