# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hPEqjgDd2u15hLzjbrkdCmcmqCAVh2Z-
"""

"""
Projeto: Base unificada IBAMA + ANTT (um único arquivo final)
Autor: OpenAI
Objetivo:
- Ler o CSV bruto do IBAMA (RAPP - Transporte de Produtos Químicos Perigosos ou Combustíveis)
- Ler um ou vários CSVs da ANTT (Certificados de Produtos Perigosos)
- Filtrar apenas anos 2023, 2024 e 2025
- Filtrar apenas registros ligados a São Paulo (SP)
- Padronizar os dois conjuntos em um único layout
- Gerar um único arquivo final:
    base_unificada_ibama_antt_2023_2025_sp.csv

Observações:
- O script funciona offline.
- CSV não tem "sheet". Por isso a saída principal é um único CSV.
- Se quiser gerar um preview em Excel depois, há uma flag opcional no começo.
"""

from __future__ import annotations

import csv
import re
import sys
import unicodedata
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import pandas as pd


# ============================================================
# CONFIGURAÇÕES
# ============================================================

# Se quiser travar o caminho manualmente, preencha as variáveis abaixo.
# Exemplo:
# IBAMA_CSV_PATH = r"C:\Users\omigu\Desktop\Analide de cargas\relatorio.csv"
# ANTT_INPUT_PATH = r"C:\Users\omigu\Desktop\Analide de cargas\antt"

IBAMA_CSV_PATH: Optional[str] = None
ANTT_INPUT_PATH: Optional[str] = None

# Se False, o script procura automaticamente os arquivos na pasta do .py e subpastas.
AUTO_SEARCH = True

# Pasta de saída
OUTPUT_DIR_NAME = "saida_unificada_ibama_antt"

# Arquivo final único
OUTPUT_UNIFIED_CSV = "base_unificada_ibama_antt_2023_2025_sp.csv"

# Opcional: gerar também um preview em Excel com uma única aba "Base preview"
GERAR_PREVIEW_XLSX = False
OUTPUT_PREVIEW_XLSX = "base_unificada_ibama_antt_preview.xlsx"

# Filtros principais
ANOS_DESEJADOS = {2023, 2024, 2025}
UF_FOCO = "SP"

# Leitura em blocos do IBAMA
CHUNK_SIZE_IBAMA = 200_000

# Limite de linhas no preview Excel, se ativado
MAX_LINHAS_PREVIEW = 50_000


# ============================================================
# FUNÇÕES UTILITÁRIAS
# ============================================================

def log(msg: str) -> None:
    print(msg, flush=True)


def normalize_text(value: object) -> str:
    """Normaliza texto: tira acentos, espaços extras e pontuação pesada."""
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return ""
    text = str(value).strip()
    if not text:
        return ""
    text = unicodedata.normalize("NFKD", text)
    text = "".join(ch for ch in text if not unicodedata.combining(ch))
    text = text.replace("\n", " ").replace("\r", " ").replace("\t", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def normalize_col(col: object) -> str:
    text = normalize_text(col).lower()
    text = re.sub(r"[^a-z0-9]+", "_", text)
    text = re.sub(r"_+", "_", text).strip("_")
    return text


def ensure_parent_dir(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def detect_encoding(file_path: Path) -> str:
    """Tenta detectar um encoding comum de forma simples e robusta."""
    candidates = ["utf-8-sig", "utf-8", "cp1252", "latin1"]
    raw = file_path.read_bytes()[:100_000]
    for enc in candidates:
        try:
            raw.decode(enc)
            return enc
        except UnicodeDecodeError:
            continue
    return "latin1"


def detect_separator(file_path: Path, encoding: str) -> str:
    """Tenta descobrir o separador do CSV lendo um pedaço do arquivo."""
    sample = file_path.read_text(encoding=encoding, errors="ignore")[:20_000]
    try:
        dialect = csv.Sniffer().sniff(sample, delimiters=";,|\t")
        return dialect.delimiter
    except Exception:
        # fallback simples
        counts = {sep: sample.count(sep) for sep in [";", ",", "|", "\t"]}
        best_sep = max(counts, key=counts.get)
        return best_sep if counts[best_sep] > 0 else ";"


def clean_series(series: pd.Series) -> pd.Series:
    return (
        series.astype("string")
        .fillna("")
        .map(normalize_text)
    )


def pick_first_existing(df: pd.DataFrame, candidates: Iterable[str]) -> Optional[str]:
    for col in candidates:
        if col in df.columns:
            return col
    return None


def coalesce_columns(df: pd.DataFrame, candidates: Iterable[str]) -> pd.Series:
    cols = [c for c in candidates if c in df.columns]
    if not cols:
        return pd.Series([""] * len(df), index=df.index, dtype="string")
    result = clean_series(df[cols[0]])
    for col in cols[1:]:
        current = clean_series(df[col])
        result = result.mask(result.eq(""), current)
    return result


def to_year_series(series: pd.Series) -> pd.Series:
    extracted = (
        series.astype("string")
        .fillna("")
        .str.extract(r"(\d{4})", expand=False)
    )
    return pd.to_numeric(extracted, errors="coerce").astype("Int64")


def to_numeric_series(series: pd.Series) -> pd.Series:
    s = series.astype("string").fillna("").str.strip()

    # tenta detectar formato brasileiro com milhar "." e decimal ","
    has_comma = s.str.contains(",", regex=False, na=False)
    has_dot = s.str.contains(".", regex=False, na=False)

    # converte:
    # 1.234,56 -> 1234.56
    # 1234,56 -> 1234.56
    # 1234.56 -> 1234.56
    s = s.str.replace(".", "", regex=False)
    s = s.str.replace(",", ".", regex=False)

    # caso original fosse só ponto decimal, acima removeria o ponto.
    # então vamos tentar recuperar via regex a partir do texto original quando necessário.
    num = pd.to_numeric(s, errors="coerce")

    return num


def combine_uf_municipio(uf: pd.Series, municipio: pd.Series) -> pd.Series:
    uf_clean = clean_series(uf).str.upper()
    mun_clean = clean_series(municipio)
    combined = mun_clean.mask(mun_clean.eq(""), "").astype("string")
    return combined.where(combined.eq(""), combined + " - " + uf_clean).mask(combined.eq(""), uf_clean)


def classify_product(text_series: pd.Series) -> pd.Series:
    s = clean_series(text_series).str.lower()

    combustivel = (
        s.str.contains("combust", na=False) |
        s.str.contains("gasolina", na=False) |
        s.str.contains("etanol", na=False) |
        s.str.contains("alcool", na=False) |
        s.str.contains("diesel", na=False) |
        s.str.contains("oleo combust", na=False) |
        s.str.contains("querosene", na=False) |
        s.str.contains("glp", na=False) |
        s.str.contains("gpl", na=False)
    )
    return pd.Series(
        ["Combustível" if x else "Carga perigosa" for x in combustivel],
        index=text_series.index,
        dtype="string",
    )


def classify_action_plan(plan_series: pd.Series) -> pd.Series:
    s = clean_series(plan_series).str.lower()
    has_plan = (
        s.str.contains("sim", na=False) |
        s.str.contains("possui", na=False) |
        s.str.contains("plano", na=False) |
        s.str.contains("emerg", na=False)
    )
    return pd.Series(
        ["Plano informado" if x else "Sem informação clara" for x in has_plan],
        index=plan_series.index,
        dtype="string",
    )


def filter_sp_rows(df: pd.DataFrame) -> pd.DataFrame:
    possible_uf_cols = [
        "uf",
        "estado",
        "uf_origem",
        "uf_destino",
        "uf_estabelecimento",
        "uf_municipio",
    ]
    possible_mun_cols = [
        "municipio",
        "municipio_origem",
        "municipio_destino",
        "municipio_estabelecimento",
        "destino",
        "origem",
    ]

    mask = pd.Series(False, index=df.index)

    for col in possible_uf_cols:
        if col in df.columns:
            mask = mask | clean_series(df[col]).str.upper().eq(UF_FOCO)

    for col in possible_mun_cols:
        if col in df.columns:
            mask = mask | clean_series(df[col]).str.lower().str.contains("sao paulo", na=False)

    return df[mask].copy()


def remove_duplicate_columns(df: pd.DataFrame) -> pd.DataFrame:
    if df.columns.duplicated().any():
        df = df.loc[:, ~df.columns.duplicated()].copy()
    return df


# ============================================================
# BUSCA DE ARQUIVOS
# ============================================================

def is_output_path(path: Path) -> bool:
    parts = {part.lower() for part in path.parts}
    return OUTPUT_DIR_NAME.lower() in parts


def find_ibama_csv(base_dir: Path) -> Optional[Path]:
    candidates: List[Path] = []
    for path in base_dir.rglob("*.csv"):
        if is_output_path(path):
            continue
        name = path.name.lower()
        if name == "relatorio.csv":
            return path
        if "ibama" in name or "rapp" in name or "relatorio" in name:
            candidates.append(path)
    return candidates[0] if candidates else None


def find_antt_csvs(base_dir: Path) -> List[Path]:
    found: List[Path] = []
    for path in base_dir.rglob("*.csv"):
        if is_output_path(path):
            continue
        name = path.name.lower()
        if "certificados-de-produtos-perigosos" in name or "antt" in name or "certificados" in name:
            found.append(path)
    return sorted(set(found))


# ============================================================
# MAPEAMENTO DE COLUNAS - IBAMA
# ============================================================

IBAMA_ALIASES: Dict[str, List[str]] = {
    "ano_ref": ["ano", "ano_referencia", "exercicio", "ano_base"],
    "empresa": ["razao_social", "empresa", "nome_empresa", "denominacao"],
    "cnpj": ["cnpj", "cnpj_empresa"],
    "uf_estabelecimento": ["uf", "estado", "sigla_uf", "uf_estab"],
    "municipio_estabelecimento": ["municipio", "cidade", "municipio_estab"],
    "produto": ["produto", "descricao_produto", "prod_quimico", "nome_produto"],
    "quantidade": ["quantidade", "qtd", "quantidade_transportada", "volume", "peso"],
    "unidade_medida": ["unidade_medida", "unidade", "medida", "un_medida"],
    "modal": ["tipo_transporte", "modal", "modal_transporte", "meio_transporte"],
    "armazenamento": ["tipo_armazenamento", "armazenamento", "forma_armazenamento"],
    "plano_acao": ["plano_emergencia", "plano_de_emergencia", "plano", "plano_acao"],
    "uf_origem": ["uf_origem", "estado_origem", "origem_uf"],
    "municipio_origem": ["municipio_origem", "cidade_origem", "origem_municipio"],
    "uf_destino": ["uf_destino", "estado_destino", "destino_uf"],
    "municipio_destino": ["municipio_destino", "cidade_destino", "destino_municipio"],
}

def map_ibama_columns(df: pd.DataFrame) -> pd.DataFrame:
    original_cols = list(df.columns)
    norm_map = {col: normalize_col(col) for col in original_cols}
    rename_map: Dict[str, str] = {}
    used_targets = set()

    for original, norm in norm_map.items():
        for target, aliases in IBAMA_ALIASES.items():
            if target in used_targets:
                continue
            if norm == target or norm in aliases or any(alias == norm for alias in aliases):
                rename_map[original] = target
                used_targets.add(target)
                break

    df = df.rename(columns=rename_map)
    df.columns = [normalize_col(c) for c in df.columns]
    df = remove_duplicate_columns(df)

    # garante colunas essenciais
    for col in IBAMA_ALIASES.keys():
        if col not in df.columns:
            df[col] = pd.NA

    return df


# ============================================================
# MAPEAMENTO DE COLUNAS - ANTT
# ============================================================

ANTT_BASE_ALIASES: Dict[str, List[str]] = {
    "ano_ref": ["ano", "ano_referencia", "exercicio"],
    "mes_ref": ["mes", "mes_referencia", "mes_ref"],
    "uf": ["uf", "sigla_uf", "estado", "unidade_federacao"],
    "municipio": ["municipio", "cidade", "nome_municipio"],
    "empresa": ["empresa", "razao_social", "transportador", "nome_empresa"],
    "tipo_certificado": ["tipo_certificado", "certificado", "tipo"],
    "quantidade": ["quantidade", "qtd", "total", "numero", "quantidade_certificados"],
}

ANTT_CERT_COLUMNS = {
    "civ": ["civ"],
    "cipp": ["cipp"],
    "ctpp": ["ctpp"],
}

def map_antt_columns(df: pd.DataFrame) -> pd.DataFrame:
    original_cols = list(df.columns)
    norm_map = {col: normalize_col(col) for col in original_cols}
    rename_map: Dict[str, str] = {}
    used_targets = set()

    for original, norm in norm_map.items():
        for target, aliases in ANTT_BASE_ALIASES.items():
            if target in used_targets:
                continue
            if norm == target or norm in aliases or any(alias == norm for alias in aliases):
                rename_map[original] = target
                used_targets.add(target)
                break

    # colunas wide típicas CIV/CIPP/CTPP
    for original, norm in norm_map.items():
        for target, aliases in ANTT_CERT_COLUMNS.items():
            if norm == target or norm in aliases:
                rename_map[original] = target

    df = df.rename(columns=rename_map)
    df.columns = [normalize_col(c) for c in df.columns]
    df = remove_duplicate_columns(df)

    return df


# ============================================================
# PROCESSAMENTO IBAMA
# ============================================================

UNIFIED_COLUMNS = [
    "fonte",
    "tipo_registro",
    "ano_ref",
    "mes_ref",
    "uf",
    "municipio",
    "empresa",
    "cnpj",
    "produto",
    "categoria",
    "quantidade",
    "unidade_medida",
    "modal",
    "origem",
    "destino",
    "armazenamento",
    "plano_acao",
    "certificado_tipo",
]

def build_unified_ibama_chunk(df: pd.DataFrame) -> pd.DataFrame:
    df = map_ibama_columns(df)

    # cria colunas limpas
    ano = to_year_series(df["ano_ref"])
    empresa = clean_series(df["empresa"])
    cnpj = clean_series(df["cnpj"])
    uf_estab = clean_series(df["uf_estabelecimento"]).str.upper()
    municipio_estab = clean_series(df["municipio_estabelecimento"])
    produto = clean_series(df["produto"])
    quantidade = pd.to_numeric(df["quantidade"], errors="coerce")
    unidade = clean_series(df["unidade_medida"])
    modal = clean_series(df["modal"])
    armazenamento = clean_series(df["armazenamento"])
    plano = clean_series(df["plano_acao"])
    uf_origem = clean_series(df["uf_origem"]).str.upper()
    mun_origem = clean_series(df["municipio_origem"])
    uf_destino = clean_series(df["uf_destino"]).str.upper()
    mun_destino = clean_series(df["municipio_destino"])

    # filtro anos
    mask_year = ano.isin(list(ANOS_DESEJADOS))

    # filtro SP
    mask_sp = (
        uf_estab.eq(UF_FOCO) |
        uf_origem.eq(UF_FOCO) |
        uf_destino.eq(UF_FOCO) |
        municipio_estab.str.lower().eq("sao paulo") |
        mun_origem.str.lower().eq("sao paulo") |
        mun_destino.str.lower().eq("sao paulo")
    )

    mask = mask_year & mask_sp
    if not mask.any():
        return pd.DataFrame(columns=UNIFIED_COLUMNS)

    uf_main = uf_estab.mask(uf_estab.eq(""), uf_origem).mask(
        uf_estab.eq("") & uf_origem.eq(""), uf_destino
    )
    municipio_main = municipio_estab.mask(municipio_estab.eq(""), mun_origem).mask(
        municipio_estab.eq("") & mun_origem.eq(""), mun_destino
    )

    origem = combine_uf_municipio(uf_origem, mun_origem)
    destino = combine_uf_municipio(uf_destino, mun_destino)

    unified = pd.DataFrame({
        "fonte": "IBAMA",
        "tipo_registro": "transporte_armazenamento",
        "ano_ref": ano,
        "mes_ref": pd.NA,
        "uf": uf_main,
        "municipio": municipio_main,
        "empresa": empresa,
        "cnpj": cnpj,
        "produto": produto,
        "categoria": classify_product(produto),
        "quantidade": quantidade,
        "unidade_medida": unidade,
        "modal": modal,
        "origem": origem,
        "destino": destino,
        "armazenamento": armazenamento,
        "plano_acao": classify_action_plan(plano),
        "certificado_tipo": pd.NA,
    })

    unified = unified[mask].copy()
    unified = unified.drop_duplicates()
    return unified


def process_ibama_csv(csv_path: Path) -> pd.DataFrame:
    encoding = detect_encoding(csv_path)
    sep = detect_separator(csv_path, encoding)
    log(f"[IBAMA] Arquivo: {csv_path}")
    log(f"[IBAMA] Encoding detectado: {encoding}")
    log(f"[IBAMA] Separador detectado: {repr(sep)}")

    chunks_result: List[pd.DataFrame] = []
    total_lido = 0
    total_mantido = 0

    reader = pd.read_csv(
        csv_path,
        sep=sep,
        encoding=encoding,
        dtype="string",
        chunksize=CHUNK_SIZE_IBAMA,
        engine="python",
    )

    for i, chunk in enumerate(reader, start=1):
        total_lido += len(chunk)
        unified_chunk = build_unified_ibama_chunk(chunk)
        total_mantido += len(unified_chunk)
        if not unified_chunk.empty:
            chunks_result.append(unified_chunk)
        log(f"[IBAMA] Chunk {i}: lidas={len(chunk):,} | mantidas={len(unified_chunk):,}")

    if chunks_result:
        result = pd.concat(chunks_result, ignore_index=True)
    else:
        result = pd.DataFrame(columns=UNIFIED_COLUMNS)

    log(f"[IBAMA] Total lido: {total_lido:,}")
    log(f"[IBAMA] Total mantido após filtros: {total_mantido:,}")
    if not result.empty:
        anos = sorted(result["ano_ref"].dropna().astype(int).unique().tolist())
        log(f"[IBAMA] Anos encontrados após filtro: {anos}")
    return result


# ============================================================
# PROCESSAMENTO ANTT
# ============================================================

def build_unified_antt_df(df: pd.DataFrame, source_name: str) -> pd.DataFrame:
    df = map_antt_columns(df)

    # caso wide: colunas civ/cipp/ctpp
    cert_cols_present = [c for c in ["civ", "cipp", "ctpp"] if c in df.columns]
    if cert_cols_present:
        id_vars = [c for c in ["ano_ref", "mes_ref", "uf", "municipio", "empresa"] if c in df.columns]
        melted = df.melt(
            id_vars=id_vars,
            value_vars=cert_cols_present,
            var_name="certificado_tipo",
            value_name="quantidade",
        )
        df = melted
        if "tipo_certificado" not in df.columns:
            df["tipo_certificado"] = df["certificado_tipo"]
    else:
        if "certificado_tipo" not in df.columns:
            if "tipo_certificado" in df.columns:
                df["certificado_tipo"] = df["tipo_certificado"]
            else:
                df["certificado_tipo"] = pd.NA

    # garante colunas
    for col in ["ano_ref", "mes_ref", "uf", "municipio", "empresa", "tipo_certificado", "quantidade", "certificado_tipo"]:
        if col not in df.columns:
            df[col] = pd.NA

    ano = to_year_series(df["ano_ref"])
    mes = pd.to_numeric(df["mes_ref"], errors="coerce").astype("Int64")
    uf = clean_series(df["uf"]).str.upper()
    municipio = clean_series(df["municipio"])
    empresa = clean_series(df["empresa"])
    certificado_tipo = clean_series(df["certificado_tipo"]).str.upper()
    quantidade = pd.to_numeric(df["quantidade"], errors="coerce")

    mask_year = ano.isin(list(ANOS_DESEJADOS))
    mask_sp = uf.eq(UF_FOCO) | municipio.str.lower().eq("sao paulo")
    mask = mask_year & mask_sp

    unified = pd.DataFrame({
        "fonte": "ANTT",
        "tipo_registro": "certificacao",
        "ano_ref": ano,
        "mes_ref": mes,
        "uf": uf,
        "municipio": municipio,
        "empresa": empresa,
        "cnpj": pd.NA,
        "produto": pd.NA,
        "categoria": "Certificação",
        "quantidade": quantidade,
        "unidade_medida": "certificados",
        "modal": "Rodoviário",
        "origem": pd.NA,
        "destino": pd.NA,
        "armazenamento": pd.NA,
        "plano_acao": pd.NA,
        "certificado_tipo": certificado_tipo,
    })

    unified = unified[mask].copy()
    unified = unified.drop_duplicates()
    return unified


def process_antt_csvs(csv_paths: List[Path]) -> pd.DataFrame:
    frames: List[pd.DataFrame] = []

    if not csv_paths:
        log("[ANTT] Nenhum CSV da ANTT foi encontrado.")
        return pd.DataFrame(columns=UNIFIED_COLUMNS)

    for path in csv_paths:
        encoding = detect_encoding(path)
        sep = detect_separator(path, encoding)
        log(f"[ANTT] Arquivo: {path}")
        log(f"[ANTT] Encoding detectado: {encoding}")
        log(f"[ANTT] Separador detectado: {repr(sep)}")
        try:
            df = pd.read_csv(
                path,
                sep=sep,
                encoding=encoding,
                dtype="string",
                engine="python",
            )
            unified = build_unified_antt_df(df, path.name)
            log(f"[ANTT] Linhas lidas={len(df):,} | mantidas={len(unified):,}")
            if not unified.empty:
                frames.append(unified)
        except Exception as e:
            log(f"[ANTT] Erro ao ler {path.name}: {e}")

    if frames:
        result = pd.concat(frames, ignore_index=True).drop_duplicates()
    else:
        result = pd.DataFrame(columns=UNIFIED_COLUMNS)

    if not result.empty:
        anos = sorted(result["ano_ref"].dropna().astype(int).unique().tolist())
        log(f"[ANTT] Anos encontrados após filtro: {anos}")

    return result


# ============================================================
# GERAÇÃO DE SAÍDA
# ============================================================

def save_unified_csv(df: pd.DataFrame, output_path: Path) -> None:
    ensure_parent_dir(output_path)
    # força ordem das colunas
    for col in UNIFIED_COLUMNS:
        if col not in df.columns:
            df[col] = pd.NA
    df = df[UNIFIED_COLUMNS].copy()

    # ordena para facilitar leitura
    sort_cols = [c for c in ["ano_ref", "mes_ref", "fonte", "uf", "municipio", "empresa"] if c in df.columns]
    df = df.sort_values(sort_cols, na_position="last").reset_index(drop=True)

    df.to_csv(output_path, index=False, sep=";", encoding="utf-8-sig")
    log(f"[OK] Arquivo final gerado: {output_path}")


def save_preview_xlsx(df: pd.DataFrame, output_path: Path) -> None:
    preview = df.head(MAX_LINHAS_PREVIEW).copy()
    ensure_parent_dir(output_path)
    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        preview.to_excel(writer, sheet_name="Base preview", index=False)
        ws = writer.sheets["Base preview"]
        ws.auto_filter.ref = ws.dimensions
        ws.freeze_panes = "A2"
    log(f"[OK] Preview Excel gerado: {output_path}")


# ============================================================
# MAIN
# ============================================================

def main() -> None:
    base_dir = Path(__file__).resolve().parent
    output_dir = base_dir / OUTPUT_DIR_NAME
    output_dir.mkdir(parents=True, exist_ok=True)

    # Descobrir arquivos
    if IBAMA_CSV_PATH:
        ibama_path = Path(IBAMA_CSV_PATH)
    elif AUTO_SEARCH:
        ibama_path = find_ibama_csv(base_dir)
    else:
        ibama_path = None

    if ANTT_INPUT_PATH:
        antt_path = Path(ANTT_INPUT_PATH)
        if antt_path.is_dir():
            antt_files = sorted(antt_path.rglob("*.csv"))
        elif antt_path.is_file():
            antt_files = [antt_path]
        else:
            antt_files = []
    elif AUTO_SEARCH:
        antt_files = find_antt_csvs(base_dir)
    else:
        antt_files = []

    if ibama_path is None or not ibama_path.exists():
        raise FileNotFoundError(
            "Não encontrei o CSV do IBAMA. "
            "Coloque o relatorio.csv na mesma pasta do .py ou preencha IBAMA_CSV_PATH."
        )

    # evita confundir o CSV do IBAMA com ANTT
    antt_files = [p for p in antt_files if p.resolve() != ibama_path.resolve()]

    log("=" * 72)
    log("INÍCIO DO PROCESSAMENTO UNIFICADO IBAMA + ANTT")
    log("=" * 72)

    ibama_unified = process_ibama_csv(ibama_path)
    antt_unified = process_antt_csvs(antt_files)

    frames = []
    if not ibama_unified.empty:
        frames.append(ibama_unified)
    if not antt_unified.empty:
        frames.append(antt_unified)

    if not frames:
        raise RuntimeError("Nenhum dado válido foi encontrado após leitura e filtros.")

    unified = pd.concat(frames, ignore_index=True).drop_duplicates()

    # Limpa tipos finais
    unified["ano_ref"] = pd.to_numeric(unified["ano_ref"], errors="coerce").astype("Int64")
    if "mes_ref" in unified.columns:
        unified["mes_ref"] = pd.to_numeric(unified["mes_ref"], errors="coerce").astype("Int64")
    unified["quantidade"] = pd.to_numeric(unified["quantidade"], errors="coerce")

    anos_final = sorted(unified["ano_ref"].dropna().astype(int).unique().tolist())
    log(f"[FINAL] Anos presentes na base unificada: {anos_final}")
    log(f"[FINAL] Total de linhas na base unificada: {len(unified):,}")

    output_csv = output_dir / OUTPUT_UNIFIED_CSV
    save_unified_csv(unified, output_csv)

    if GERAR_PREVIEW_XLSX:
        output_xlsx = output_dir / OUTPUT_PREVIEW_XLSX
        save_preview_xlsx(unified, output_xlsx)

    log("=" * 72)
    log("PROCESSAMENTO CONCLUÍDO")
    log("=" * 72)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        log("\n[INTERROMPIDO] Execução cancelada pelo usuário.")
        sys.exit(1)
    except Exception as exc:
        log(f"\n[ERRO] {exc}")
        sys.exit(1)